docs/api.md
lib/routes/redirect.js
test/api.js

`action=force_auth` redirects to the `/force_auth` page on the content server. On the content server, the user must sign in with the email specified by the `email` query parameter.
fixes #190 
See mozilla/fxa-content-server#1957

feat(api): Add `action=force_auth` to GET /v1/authorization.

---

docs/api.md

Describe `email=blank` behavior, and not specified behavior.
Link to https://github.com/mozilla/fxa-content-server/pull/2027

docs(api): Update `email` behavior for GET /v1/authorization.

---

lib/server.js
test/api.js

Only blank and application/json are allow.
Closes #199 
r? @zaach

fix(api): reject requests with bad content-types

---

docs/api.md
lib/routes/destroy.js
test/api.js

A problem came up that I'm trying to revoke tokens created by implicit grants, so I don't have the client secret available. I looked at Google's API, and they don't require any authorization either (if you already have a token, things gon burn): https://developers.google.com/accounts/docs/OAuth2WebServer#tokenrevoke
@rfk r?

feat(api): allow destroying token without client_secret

---

lib/routes/client/register.js
test/api.js

This fixes some hapi response payload validation errors that could occur
when omitting optional fields in client registration:
- allow `image_uri` to be the empty string, which is the default value
- coerce `can_grant` and `whitelisted` to booleans, rather than e.g. `undefined`
fixes #203

fix(clients): fix server error when omitting optional fields in client registration

---

lib/routes/authorization.js
lib/routes/token.js
lib/server.js
test/api.js

This keeps the leniency for the POST /v1/token endpoint, but
cactches errors for misuses of other endpoints.
Closes #210 
@washort sanity checking, this doesn't break you, does it? It's only the token endpoint that receives extra parameters?

fix(api): reject requests with invalid parameters

---

lib/server.js

Minor fix I noticed when running in verbose logging. Ain't no `route.url` property.

fix(logging): use route.path in debug message, not route.url

---

Dockerfile
README.md

I've added a dockerfile and some instructions to README.md explaining how to use Docker to develop and run the oauth server. It allows for development with an IDE underneath a running container as one would normally work. This means changes and running the verifier are mostly transparent to normal development. If there are any questions feel free to ask here or in IRC.

 feat(docker): Dockerfile and README update for basic docker development workflow

---

config/awsbox.json
config/dev.json
config/test.json
lib/db/index.js

In getting setup to deploy the train-30 oauth server in production today, there was delay caused by a one-character typo in the production config, a typo in 'redirecturl' (all lower case, not camelCase 'redirectUrl'). The typo didn't exist in the stage config, which made this tedious to figure out.
Anyways, the code as written should guard against and attempt to insert a NULL into a non-NULL column.
In dev, a mispelled key will show an error message like this:
`fxa-oauth-server.db.ERROR: client.missing.keys {"key":"canGrant","name":"Firefox Hello DEV"}`
(We lose some flexibility in the config files by making keys mandatory; could consider just moving this logic to db migration files.)
NOTE: If this patch is merged, this file will need to have 'canGrant: false' added where is it missing: …

make the clients keys mandatory in the config file

---

config/dev.json

Adds clients from: https://bugzilla.mozilla.org/show_bug.cgi?id=1064505
This will be useful for devs working on these clients locally. I'm not sure if these are available on latest but we might want to create them there, too.

chore(clients): add credentials for FF/FFOS/Fennec/FxA clients in dev

---

.travis.yml

I noticed, when looking at a logs of a build on travis-ci, that node-bigint was failing to compile because `gmp.h` was not available. Not a big deal, but seems better to add libgmp-dev than not. Also future-proofs for an annoying spinner more current versions of npm. 
@rfk, @seanmonstar r?

fix(travis): install libgmp3-dev so optionaldep bigint will be built for browserid-crypto

---

bin/internal.js
lib/config.js
lib/routing.js
lib/server/config.js
lib/server/index.js
lib/server/internal.js
test/api.js
test/lib/server.js

This will allow the management APIs to be turned on in "production", but using a port that is not publicly accessible.
/cc @ckolos @ckarlof

feat(clients): move client management api to a separate port

---

lib/routes/redirect.js
test/api.js

Fixes #245.
Depends on implementation of https://github.com/mozilla/fxa-content-server/issues/2344

feat(auth): redirect to content-server oauth root by default

---

lib/routes/destroy.js
test/api.js

Fixes #236.  (And with apologies to @chilts for stealing his bug; I've been starting at oauth server response bodies for that last hour and this was really starting to grate on me...)

fix(api): ensure /destroy endpoint returns an empty object in response body

---

package.json
tasks/bump.js
tasks/version.js

to create release tags
Fixes https://github.com/mozilla/fxa-oauth-server/issues/159

chore(release): add tasks "grunt version" and "grunt version:patch" 

---

lib/config.js

Fixes #294 
I suppose named constants for DAY_MS, WEEK_MS, etc. would help, or moment.js/other, but meh.

fix(config): set expiration.accessToken default to 2 weeks

---

docs/api.md
lib/routes/authorization.js
test/api.js

Fixes #292.
The new parameter is optional when `response_type=token` and forbidden when `response_type=code`.
Assumptions:
* It is expressed in seconds.
* The maximum should be `config.get(expiration.accessToken)`.

feat(api): add ttl parameter to POST /authorization

---

lib/db/mysql/index.js
lib/routes/client/list.js
lib/routes/client/register.js
test/api.js

fixes #301 
But this should only be merged after GH-302 
Puts back the parts that remove references to a `whitelisted` column, which can be dropped AFTER the train with this change is live and stable.
r? @seanmonstar

fix(sql): remove references to the `whitelisted` column; this is now the `trusted` column

---

lib/config.js

refactor(config): Use human-readable duration values in config

---

lib/db/mysql/index.js
package.json
test/db/index.js
test/db/mysql.js
test/lib/mocks.js

Fixes #291.
Although the fix itself was straightforward, adding tests for it was less so. There were no tests in place for `lib/db/mysql/index.js` and I didn't want to make a change without adding appropriate tests. To that end, I've introduced two new dev dependencies, `sinon` and `mockery`.
You'll notice some fairly ugly boilerplate at the top of the new test module, `test/db/mysql.js`. This is partly because there are a lot of dependencies to mock but also because the blanket coverage tool rewrites `require` paths in the instrumented code, so we need to do a bit of magic to ensure mockery is handling them correctly.
You may or may not be thinking that this seems like a lot of hoops to jump through, just for testing a new call to `process.exit()`. I think they're worth it though, …

fix(server): exit if db patch level is wrong

---

.travis.yml

We should use npm@2 since the default with nodejs 0.10 is an obsolete and flaky version of npm (1.4.28). We already build production with npm@2.6.1; I'm not particularly concerned with what version travis uses as long as it in the 2.x series.
r? - @seanmonstar - note no need to merge this before train-42 is cut.

chore(travis): use npm@2 for more stable installs

---

lib/config.js
lib/env.js
lib/events.js
lib/server/index.js
lib/server/internal.js

While abrupt, forgetting to delete user information is a big deal, so
this will prevent the server from running as long as the event queue is
not setup.
BREAKING CHANGE: Server will fail to start up if `config.events` is not
set with values when in production.
See #310 
cc @ckolos: I noticed the puppet-config is missing these values, so they will need to be updated.

fix(events): require events to be configured in production

---

lib/db/mysql/index.js
test/db/mysql.js

Hey, @seanmonstar - this is similar to the change in patch level restrictions we made for fxa-auth-db-mysql. It isn't always true that there is one db patch in each train, and train-42 has two (that amount to a no-op, but that's a different story). 
I will have to backport this to v0.41.1, where it will be slightly different due to other changes to this file. 
But first, I wanted to get this in master. 
r?

fix(db): we need to enforce only a minimum patch level (not {n,n+1})

---

lib/db/index.js

To change secrets is a precarious dance with live servers. It would be better if this could did not muck with the database at startup. 

fix(db): don't change client database at startup; footgun

---

lib/routes/root.js
lib/routing.js
test/server.js

Fixes #321 . This preserves the `/` route but extends the output to include the git source repo, and adds an alternate route `/__version__` that serves the same content and a couple of more tests of the output. 
So content used to look like
```
{
"version": "0.44.0",
"commit": "e31f764c6dcfaeecc8e0ac531002eeab279137ea"
}
```
and is now like:
```
{
"version": "0.44.0",
"commit": "e31f764c6dcfaeecc8e0ac531002eeab279137ea",
"source": "git://github.com/mozilla/fxa-oauth-server.git"
}
```

chore(version): add /__version__ route with source repo

---

lib/routes/root.js

Apologies for futzing with this. 
I realized that git-config should use an explicit path to the config location (because, on fxa-dev boxes, fxa-oauth-server starts from `/`, not the checked out repo, and so can't find the config). 
Also, eliminated and unused IFFE, and added a newline to the output because nicer.

fix(version): use explicit path with git-config

---

lib/db/mysql/index.js
test/db/mysql.js
test/lib/mocks.js

I meant to do this ages ago but forgot about it until it got mentioned in IRC the other day.
When I added the mocking stuff to this repo, I'd never used `proxyquire` before and assumed that it worked the same way as `mockery`. Of course, it doesn't.
So all the register/deregister module-cache hoop-jumping was completely unnecessary. Instead I should just have used the object returned by `proxyquire` directly.
The one thing that doesn't work using this approach is mocking the logger. So to stop those tests from failing, I've added an option for injecting the mock logger to `MysqlStore.connect`.

chore(tests): remove weird mocking magic

---

lib/db/mysql/patch.js
lib/db/mysql/patches/patch-011-012.sql
lib/db/mysql/patches/patch-012-011.sql

Fixes #267, which we had to revert the first time around.  Patch number 11 is already taken by #336, so I used 12 here and will have to rebase this atop that one once it merges.  The schema document is already sans `whitelisted` because that wasn't reverted when we rolled this back the first time around.
@seanmonstar r?

chore(clients): remove deprecated 'whitelisted' column from clients table

---

.travis.yml

I tried to update to grunt-nsp but that spewed errors about extraneous modules under node_modules/grunt-nsp. So just removing this broken test to fix travis. r? @seanmonstar

fix(travis): remove broken validate shrinkwrap

---

.travis.yml
npm-shrinkwrap.json
package.json

Needs to use my fork of node-generate-rsa-keypair to run on node 4.x. I left a PR on that repo to get that officially upgraded to 4.x, although maybe we could consider doing something on our own instead of using that module.

fix(travis): build on node 0.10, 0.12, 4, no allowed failures

---

config/dev.json
config/test.json
docs/api.md
lib/config.js
lib/routes/jwks.js
lib/routes/token.js
lib/routing.js
test/api.js

Requesting authorization with the scope `openid` will result in an
`id_token` property being returned along with the `access_token`.
Closes #362
-----
Known missing:

feat(openid): add initial OpenID Connect support

---

lib/token.js
test/api.js

We ran into some operational issues when deploying this, backing it out
so that we can get the rest of train-53 out the door.
@jrgm r?

revert(tokens): dont reject expired tokens, again

---

config/dev.json
config/test.json
lib/config.js
npm-shrinkwrap.json
package.json
scripts/gen_keys.js

This PR adds the ability to generate dynamic OpenId keys which is needed by https://github.com/mozilla/fxa-dev/issues/212. The files, key.json and oldKey.json are created via npm postinstall script. If the environment configuration specifies a `keyPath` or `oldKeyPath`, then these keys will be loaded into the openid configuration.

fix(openid): Dynamicly generate openid keys 

---

config/test.json
lib/db/index.js
lib/db/memory.js
lib/db/mysql/index.js
lib/db/mysql/patch.js
lib/db/mysql/patches/patch-013-014.sql
lib/db/mysql/patches/patch-014-013.sql
lib/db/mysql/schema.sql
lib/routes/token.js
test/api.js

This PR adds initial support for changing a client's secret key with no downtime. Adds a new database column `hashSecretPrevious` and updated logic in `/token` route to check if client using previous key.
Fixes #317

Add support for changing client key with no downtime

---

npm-shrinkwrap.json
package.json

1. `npm-shrinkwrap.json` was dropped. This puts it back.
2. In getting travis tests to run with nodejs 4, generate-rsa-keypair wouldn't compile. So, I forked it, fixed it to use nan@2 and submitted the patch upstream. Now that upstream released that (a while ago), my branch is not needed, so this switches the dependency back to it.
r? @rfk or @seanmonstar ?

Fix a couple of dependency related things

---

bin/purge_expired_tokens.js
lib/db/mysql/index.js
test/db/index.js

This tunes up bin/purge_expired_tokens.js:
1) log uncaughtException; minimum log level of info
- moves to more conventional logging in this repo and nothing below log level info
- prints out any uncaughtException
2) use db.getClient() to check for unknown clientId
- the `clients` table is the one that matters
3) set db.autoUpdateClients config to false
- No point in doing this in dev for the purposes of this script, and disabled in prod/stage.
4) moar logging
- because https://youtu.be/-fQGPZTECYs?t=24
5) Promise.delay takes milliseconds; also allow subsecond delay for command line option
- nuff said
r? - @vbudhram 
Maybe look at each commit separately, instead of the aggregate.

tuneups for bin/purge_expired_tokens.js

---

bin/purge_expired_tokens.js
lib/db/mysql/index.js
test/db/index.js

r? - @vbudhram 
There is more than one ID that needs to be preserved, so this makes it possible.

fix(purge-expired): accept a list of pocket-id's

---

.travis.yml

Changes to travis:
- drop 0.10, add 6
- always g++-4.8
- use the default npm that comes with node (4 => 2, 6 => 3)
- npm install automagically happens for node projects; extra logic no longer needed.

fix(travis): test on node4/node6 with default npm & g++-4.8

---

test/api.js

The API tests were a strange mixture of returning promises and using the done() callback; this makes them all uniformly use promises.

chore(tests): Uniformly use promises rather than done() callback.

---

lib/config.js
lib/token.js
test/api.js

This implements the approach suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1320216#c1 to start more strictly enforcing access token expiry.  It allows old tokens to remain in their current "dont expire unless physically deleted" state, while any newly-issued tokens will expire normally.
@seanmonstar r?
@jrgm let me know if you have any concerns about the impact of this approach on server load.  It seems like it should be OK as it leaves the outstanding backlog of unexpired tokens alone.

Begin expiring access tokens beyond a configurable epoch.

---

lib/server/config.js
test/server.js

Add security headers (see also the commit messages).
I'm assuming these API endpoints aren't iframed anywhere.
We discussed having the webserver send these, but having this in code allows it to be tested and makes dev and prod environments more similar. Both of those things make @jrgm happy.

Enable security headers

---

npm-shrinkwrap.json
package.json
scripts/gen_keys.js
test/api.js

This PR switches from a native module to a pure JS module. No build dependencies necessary!

fix(scripts): Use pure JS module to generate RSA keypairs

---

lib/config.js
lib/server/config.js
test/api.js
test/lib/util.js
test/server.js

r? - @seanmonstar - /cc @g-k 
This is akin to the patch to profile server to set an extended cache-control header (and extend the tests to check for all the security headers).

fix(headers): add cache-control headers to api endpoints; extend tests

---

.travis.yml
package.json

r? - @vbudhram 
The `|| exit 0` is so that `npm run outdated` acts the same with npm@5 (which will exit non-zero in cases that npm < 5 did not).

fix(travis): run tests with 6 and 8

---

lib/config.js
lib/error.js
lib/routes/key_data.js
test/api.js

For a future world where the `keyRotationSecret` is actually a secret value, we should only return it to users who have proved that they *recently* know the account password.  @vladikoff r?

feat(keys): Check lastAuthAt freshness when fetching key data.

---

bin/internal.js
bin/server.js
lib/config.js
npm-shrinkwrap.json
package.json

This reverts commit d98fbcde7376a9bf8b310d44d0937a47c0b7ff1f.
So, the new strict validation is not happy if FXA_OPENID_KEY is set via the environment. Complains about:
```
Error: configuration param 'openid.key.kty' not declared in the schema
configuration param 'openid.key.n' not declared in the schema
configuration param 'openid.key.e' not declared in the schema
configuration param 'openid.key.d' not declared in the schema
configuration param 'openid.key.p' not declared in the schema
configuration param 'openid.key.q' not declared in the schema
configuration param 'openid.key.dp' not declared in the schema
configuration param 'openid.key.dq' not declared in the schema
configuration param 'openid.key.qi' not declared in the schema
configuration param 'openid.key.kid' not declared in the …
```

Revert "fix(config): mark config sentryDsn and mysql password sensitive (#511)

---

lib/routes/authorization.js
test/api.js

As noted in https://github.com/mozilla/fxa-oauth-server/issues/515, untrusted reliers currently can't request the `openid` scope, and hence can't use the OIDC id_token flow.  I don't see any risk to allowing them to request it, since the id_token doesn't directly contain any profile information, they still have to request other scopes like `profile:email` in order to be able to access profile data.
@vbudhram r?

feat(openid): Allow untrusted reliers to request `openid` scope.

---

scripts/test-local.sh

Sorry Glog, but I'm pretty sure you're a typo; @mozilla/fxa-devs r?

fix(scripts): Fix varname typo in test runner script.

---

docs/api.md
lib/routes/redirect.js
test/api.js

Use the `action=email` query parameter to trigger the
email-first flow. Redirects to `/` on the content
server, propagating the `action=email` query parameter.
fixes #539 
@mozilla/fxa-devs - r?

feat(email-first): Add support for the email-first flow.

---

lib/routes/authorization.js
test/api.js

The `POST /authorization` API returns a formatted redirect URL its its JSON response.  However, AFAICT everyone who calls that API ends up parsing the code out of the query parameters, including [content-server](https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/models/auth_brokers/oauth.js#L24), [PyFxA](https://github.com/mozilla/PyFxA/blob/master/fxa/oauth.py#L135), and as you can see from this PR, our own test cases.
So I figure, why not just return it directly and save everyone the trouble?  We can keep the `redirect` field for backwards-compatibility while also directly returning the `code` and `state` fields that would otherwise need to be parsed from its query params.
@mozilla/fxa-devs r?

feat(authorization): Directly return `code` in authorization response.

---

lib/validators.js
test/api.js

A quick fix for #547; we don't do anything with these URIs other than tunnel them around to the content-server, which does its own additional validation.  @mozilla/fxa-devs r?
Fixes #547.

fix(validation): Allow redirect uris with existing query params.

---

lib/routes/authorization.js
lib/routes/key_data.js
lib/validators.js
test/api.js

The sync tokenserver does a special check for "fxa-tokenVerified" in order to enforce the use of session verification when accessing sync:
https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/views.py#L140
Let's apply the same check here before granting any scopes that come with keys.  In theory the user should *always* have a verified assertion when requesting one of these scopes, because they will have just done a keyfetch that would have required it.  But there is at least one known series of calls to our backend that can yield keys without doing a verification, so it makes sense to double-check here and avoid any loopholes.
@vladikoff r?

feat(authorization): Require tokenVerified=true when granting key-bearing scopes.

---

lib/db/mysql/index.js

It turns out that the mysql variant of https://github.com/mozilla/fxa-oauth-server-private/pull/9 was buggy, and would aggregate all clients into a single record with id of "undefined" rather than producing one record per client id.
It's a simple fix that we should point-release to train-115; @vladikoff r?
But it's also an indication that the CI in fxa-oauth-server-private is only running tests against the in-memory db, not against mysql.  @jrgm @jbuck which do you think would be a simpler way to fix that - having circle run tests against the mysql backend, or adding travis to the private repo?

fix(mysql): Correctly aggregate tokens by clientid.

---

lib/db/memory.js
lib/db/mysql/index.js
lib/routes/client-tokens/delete.js
test/api.js
test/db/index.js

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1320218#c3, revoking access for an OAuth client should revoke everything, including any as-yet-unclaimed authorization codes.

feat(codes): Delete authorization codes when revoking client access.

---

.circleci/config.yml
Dockerfile-build
Dockerfile-test

This is similar to mozilla/fxa-profile-server#330. It builds from a base image that has tools that can build binary node extensions, and secondly, checks the install with `npm install --production`.
The net gain is 3MB from the production image. (A `--squash` would recoup about 8MB from that image, but not bothering with `--squash` in this PR).
r? - @vladikoff

Dockerpush fix docker use base builder run npm ls production

---

config/dev.json

This enables the content server functional tests to run locally
when using fxa-local-dev
fixes mozilla/fxa-content-server#6362
@vladikoff - r?

fix(config): For dev, the openid issuer is http://127.0.0.1:3030

---

config/dev.json

ref https://github.com/mozilla/fxa-dev/blob/85b8742e2d8201e13fe1d4563f243e2e0034877e/roles/oauth/templates/config.json.j2#L50
ref https://github.com/mozilla/fxa-content-server/issues/6345

fix(clients): match the notes client with fxa-dev and other envs

---

docs/api.md

I was going to link to this page and I realized we didn't put any emphasis on email first flow so I thought I would add that. I believe we all want to make it clear that it is the new preferred method for authenticating users.

fix(doc): Putting a little emphasis on email first

---

lib/routes/authorization.js
test/api.js

Fixes #593; @shane-tomlinson r?

fix(authorization): Correctly handle non-existing URL scopes during authorization

---

lib/routes/key_data.js
test/api.js

This is basically the same bug as https://github.com/mozilla/fxa-oauth-server/pull/594/files except in the `/key-data` endpoint.  @mozilla/fxa-devs r?

fix(key-data): Correctly handle non-existent scopes when finding key data

---

lib/db/mysql/index.js
lib/db/mysql/patch.js
lib/db/mysql/patches/patch-022-023.sql
lib/db/mysql/patches/patch-023-022.sql
lib/db/mysql/schema.sql

These constraints make DB migrations harder and they're really not providing us much value in practice.
Fixes #611.

fix(db): Drop foreign key constraints.

---

lib/routes/authorization.js

The content-server sends an explicit `null` here if the no `acr_values` query param is provided.  Prior to this fix, all non-2fa-requesting OAuth flows would fail with "Invalid OAuth parameters: acr_values" (which I expect will show up as functional test failures, if it hasn't already).

fix(2fa): Allow an explicit `null` value for `acr_values` param.
