mozilla/fxa-oauth-server

- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-000-001.sql
- lib/db/mysql/patches/patch-001-000.sql
- lib/db/mysql/patches/patch-001-002.sql
- lib/db/mysql/patches/patch-002-001.sql
- lib/db/mysql/schema.sql
- npm-shrinkwrap.json
- package.json
This is a work-in-progress branch to import the db-patcher functionality from fxa-auth-db-server.  Not ready for merge.
Fixes #183
> feat(db): add basic migration infrastructure to mysql backend

- config/test.json
- lib/routes/client/get.js
- test/api.js
> fix(clients): fixes client endpoint for clients with no redirect_uri

- lib/routing.js
- test/api.js
> fix(clients): support client/client_id route via the internal server

- npm-shrinkwrap.json
- package.json
- test/api.js
Hapi will be separate, since it is quite a breaking change.
> chore(dependencies): update most dependencies

- lib/browserid.js
- lib/config.js
> Pool sizes

- config/test.json
- docs/api.md
- lib/error.js
- lib/routes/authorization.js
- test/api.js
> feat(untrusted-clients): restrict scopes that untrusted clients can request

- config/dev.json
> chore(dev): add 321Done untrusted client

- bin/server.js
> fix(fatal-error): Exit with non-zero exit code for fatal errors

- lib/routes/client/register.js
> fix(clients): fixes client registration to use payload.whitelisted

- docs/api.md
> docs(verify): fix misnamed 'scopes' response property

- lib/config.js
- npm-shrinkwrap.json
- package.json
> chore(config): Update convict and switch on strict validation.

- docs/api.md
- lib/error.js
- test/api.js
Fixes the InvalidAssertions error code based on discussions in https://github.com/mozilla/fxa-oauth-server/issues/234
> Fix InvalidAssertions Error code

- lib/routes/redirect.js
- test/api.js
fixes https://github.com/mozilla/fxa-oauth-server/issues/194
> fix(api): fail on invalid action parameters

- test/api.js
> test(api): rename assertRequestParam to assertInvalidRequestParam

- config/dev.json
- config/test.json
Part of https://github.com/mozilla/fxa-oauth-server/issues/230
@seanmonstar r?
> fix(config): update redirect_uri values to not be blank

- .travis.yml
> chore(travis): Only install libgmp3-dev on Travis

- lib/db/memory.js
- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-007-006.sql
- lib/db/mysql/patches/patch-007-008.sql
- lib/db/mysql/patches/patch-008-007.sql
- lib/routes/client/list.js
- lib/routes/client/register.js
- lib/routes/token.js
- test/api.js
fixes #301
- reverts all the code changes in commit 155d2ce
- for mysql-patcher, undo rename of hashedSecret to secret,
and undo drop of column whitelisted
r? @seanmonstar
> fix(sql): undo 155d2ce; for mysql-patcher fix up that database

- test/api.js
Fixes #300 
Note: this is independent of the PR's to deal with the database changes
> fix(tests): sleep additional half second to adjust for mysql round of timestamp

- lib/token.js
Adds logging to help diagnose who is using expired tokens in #308.
> chore(logging): Log additional details for debugging expired tokens

- .travis.yml
- npm-shrinkwrap.json
- package.json
- test/api.js
just a dev dep, but now ought to work with newer node versions...
> replaced bidcrypto dep with fxa-jwtool

- package.json
> chore(package): remove main from package.json

- lib/routes/authorization.js
- lib/server/index.js
- tasks/release.js
- test/api.js
> fix(authorization): allow empty scope with implicit grant

- docs/clients.md
> chore(docs): add a note about dev envs

- lib/db/memory.js
- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-008-009.sql
- lib/db/mysql/patches/patch-009-008.sql
- lib/db/mysql/schema.sql
- lib/routes/token.js
> refactor(db): add hashedSecret column to clients

- lib/db/index.js
- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-009-010.sql
- lib/db/mysql/patches/patch-010-009.sql
- lib/db/mysql/schema.sql
> feat(db): remove clients.secret column

- npm-shrinkwrap.json
- package.json
> fix(deps): update to mozlog 2.0.2

- config/dev.json
- config/test.json
> fix(config): remove 00000... from hashedSecrets

- docs/api.md
> fix(docs): note that codes are single use

- bin/internal.js
- bin/server.js
- lib/events.js
- lib/server/index.js
- lib/server/internal.js
> fix(config): update config to use getProperties

- docs/api.md
- lib/routes/verify.js
- test/api.js
Any requests that don't opt out of receiving the email will log a
warning.
Closes #358
> feat(verify): add opt out parameter to verify endpoint

- lib/config.js
- lib/db/index.js
> fix(config): option autoUpdateClients, will be disable in prod/stage

- lib/token.js
- test/api.js
> feat(token): reject expired tokens

- lib/routes/redirect.js
- test/api.js
Re-opening https://github.com/mozilla/fxa-oauth-server/pull/371 against master, and assuming travis gives the OK, I'll carry over the r=@seanmonstar from there.
> feat(openid): Add support for OIDC `login_hint` query param.

- lib/routes/authorization.js
- npm-shrinkwrap.json
- package.json
> fix(deps): switch from URIjs to urijs

- npm-shrinkwrap.json
- package.json
/cc @jrgm @vbudhram @vladikoff
> chore(package): pin blanket to 1.1.6

- scripts/gen_keys.js
Fixes #397.  This is why comments were invented :-)
> chore(docs): Add a comment about privKey/pubKey confusion in gen_keys

- npm-shrinkwrap.json
- package.json
@seanmonstar r?; probably worth including this in train-66 tag
> chore(deps): Update request package to latest version

- lib/logging/summary.js
> fix(log): avoid crashing on bad payload

- test/db/index.js
> fix(test): encrypt refresh_token on db query

- lib/config.js
- lib/logging/summary.js
- lib/server/index.js
> fix(log): add remoteAddressChain to summary

- npm-shrinkwrap.json
- package.json
> feat(shared): add new locales

- lib/config.js
- lib/server/index.js
- lib/server/internal.js
- npm-shrinkwrap.json
- package.json
- test/hpkp.js
Ref: https://github.com/mozilla/fxa-bugzilla-mirror/issues/179
> feat(hpkp): Add the hpkp headers to all requests

- npm-shrinkwrap.json
- package.json
Ref https://github.com/mozilla/fxa-shared/issues/9
> fix(deps): update to hapi 16, add shrinkwrap scripts, update other prod deps

- config/dev.json
- config/test.json
- lib/config.js
- lib/routes/authorization.js
- test/api.js
Fixes #387
Fixes #388 
@vbudhram r?
> feat(authorization): add uri validation on the authorization endpoint

- lib/db/memory.js
- lib/db/mysql/index.js
- lib/routes/token.js
- test/api.js
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1320214; @seanmonstar r?
> fix(codes): Remove authorization codes after use.

- lib/db/memory.js
- test/api.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/421
> fix(memorydb): token createdAt used instead of client createdAt

- scripts/gen_keys.js
> fix(keys): Generate unique 'kid' field when regenerating JWK keys

- lib/db/helpers.js
- lib/db/memory.js
- lib/db/mysql/index.js
- lib/routes/client-tokens/list.js
- test/api.js
- test/db/helpers.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/431
> refactor(client): scope added in memory and sql

- lib/routes/verify.js
> fix(logs): add scope and client_id logs to verify route

- lib/db/mysql/index.js
- test/db/index.js
- test/db/mysql.js
> fix(db): ensure strict mode

- lib/routes/client-tokens/delete.js
- test/api.js
> fix(api): clean up response of client-tokens delete endpoint (#3)

- test/db/index.js
I could have used '💩', but staying classy with '𝄢'.
r? - @rfk, @vladikoff
> fix(tests): check insert of utf8mb4

- lib/routes/root.js
refs: bug 1320217 
similar to: https://github.com/mozilla/fxa-content-server/pull/4804
Fix command execution in the unlikely event the application is run from a location with a malicious or malformed directory name per rfk's suggestions in the bug mentioned above.
Functional Tests:
```
fxa-local-dev/fxa-oauth-server - [master] » curl -X GET http://localhost:9010/__version__
{
"version": "1.81.0",
"commit": "usage:git [--version] [--help] [-C <path>] [-c name=value]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a …
```
> fix(version): use cwd and env var to get version

- lib/routes/jwks.js
- scripts/gen_keys.js
This will make it easier for secops to audit our key rotation schedule.  @seanmonstar r?
> feat(keys): Add created-at timestamp to our public keys.

- lib/config.js
More config in environment variables.
> fix(config): expose more environment variables for config

- test/db/index.js
I wasn't returning the promise[1]. Also, the memory db impl should be expected to pass, not fail.
[1] e.g., https://travis-ci.org/mozilla/fxa-oauth-server/jobs/213525486#L677
> fix(test): fix unhandled rejection error with memory db impl

- npm-shrinkwrap.json
- package.json
> chore(deps): Update hapi dependency.

- lib/routing.js
- test/server.js
This PR adds the required endpoint `__lbheartbeat__` for dockerflow.
> feat(lb): Add `__lbheartbeat__` endpoint

- lib/config.js
May or may not need this, but is consistent...
> fix(config): expose clients config as OAUTH_CLIENTS

- circle.yml
> feat(docker): support feature branches

- package.json
Not currently operationl, but let's update it to latest before it is. 
> fix(newrelic): update to v2.1.0

- config/dev.json
> chore(dev): add Firefox Notes Web Extension client to development config

- docs/api.md
- lib/routes/token.js
- test/api.js
Fixes #472
@rfk @seanmonstar r?
> feat(pkce): add ability for PKCE clients to use refresh_tokens

- config/dev.json
- lib/db/memory.js
- lib/db/mysql/index.js
- lib/events.js
- test/db/index.js
- test/events.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/481
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1374032
> feat(tokens): add support for password change and reset event

- docs/api.md
- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-018-019.sql
- lib/db/mysql/patches/patch-019-018.sql
- lib/routes/authorization.js
- lib/routes/token.js
- lib/validators.js
- test/api.js
> feat(keys): add keys_jwe support

- lib/validators.js
- test/api.js
> feat(scopes): allow https:// scopes

- docs/api.md
- lib/routes/key_data.js
- lib/routing.js
- test/api.js
Sorry some extras slipped from the previous PR. Added here.
@rfk r?
Follow up for https://github.com/mozilla/fxa-oauth-server/pull/487
> feat(keys): add key-data docs, move client_id into payload

- lib/validators.js
- test/api.js
- test/routes/token.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/495
> fix(pkce): match pkce implementation to specifications

- lib/config.js
- lib/server/index.js
- npm-shrinkwrap.json
- package.json
> feat(logs): add sentry support

- lib/config.js
- lib/error.js
- lib/routes/key_data.js
- test/api.js
Reverts mozilla/fxa-oauth-server#502
> revert(keys): Check lastAuthAt freshness when fetching key data.

- config/dev.json
- config/test.json
- docs/api.md
- test/api.js
> fix(keys): replace scope key TLD

- lib/db/memory.js
- lib/db/mysql/index.js
- test/api.js
> fix(tokens): invalidate refresh tokens on client-token DELETE action

- lib/config.js
- lib/error.js
- lib/routes/key_data.js
- test/api.js
'cause I want to deploy this for debugging....
> feat(keys): Check lastAuthAt freshness when fetching key data.

- bin/internal.js
- bin/server.js
- lib/config.js
- npm-shrinkwrap.json
- package.json
r? - @vladikoff 
mark config sentryDsn, openid keys and mysql password as `sensitive`.
> fix(config): mark config sentryDsn and mysql password sensitive

- lib/routes/token.js
- test/api.js
- test/routes/token.js
This is required for strict compliance with RFC6749, which mandates that we MUST support client credentials via this method.
Fixes #513; @mozilla/fxa-devs r?
> feat(auth): Accept client credentials in the Authorization header.

- docs/service-clients.md
- lib/browserid.js
- lib/config.js
- lib/routes/authorization.js
- lib/routes/client/get.js
- test/api.js
Fixes #527 Remove deprecated `Buffer` call
> fix(buffer): #527 Migrate deprecated buffer calls

- lib/browserid.js
- lib/db/memory.js
- lib/db/mysql/index.js
- lib/db/mysql/patch.js
- lib/db/mysql/patches/patch-020-021.sql
- lib/db/mysql/patches/patch-021-020.sql
- lib/routes/authorization.js
- lib/routes/token.js
- package.json
- scripts/test-local.sh
- test/api.js
- test/browserid.js
Fixes #519.  Work-in-progress for now while I try to get all the servers stood up and talking to each other in a dev environment.
> feat(amr): Report `amr` and `acr` claims in the id_token.

- lib/logging/index.js
- test/db/index.js
- test/lib/mocks.js
Fixes #334 Mock outstanding error logs in test suite.
Also handles mozlog deprecation warning.
> fix(mock): Fixes #334 Mock outstanding error logs in test suite

- lib/routes/verify.js
- test/api.js
@vladikoff we need to remove just this parameter or drop from the response also  :
https://github.com/mozilla/fxa-oauth-server/blob/7ad1e56f95ec54dd5096937a5cb3b42585841105/lib/routes/verify.js#L23
Also this will remain as it is ?
https://github.com/mozilla/fxa-oauth-server/blob/7ad1e56f95ec54dd5096937a5cb3b42585841105/lib/token.js#L60
> refactor(email): Fixes #352 Remove ability to fetch email address 

- config/dev.json
> feat(sync): add oldsync scope

- config/test.json
- lib/routes/authorization.js
- lib/routes/token.js
- test/api.js
> fix(pkce): Don't require PKCE in the direct grant flow.

- CHANGELOG.md
- docs/api.md
- lib/db/helpers.js
- lib/db/memory.js
- lib/db/mysql/index.js
- lib/routes/client-tokens/list.js
- npm-shrinkwrap.json
- package.json
- test/db/helpers.js
- test/db/index.js
From https://github.com/mozilla/fxa-oauth-server-private/pull/9
> Merge private train-115 point-release to master

- .circleci/config.yml
> fix(ci): Run MySQL tests in Circle

- lib/routes/token.js
- lib/util.js
- test/api.js
Fixes #509 
This PR adds the `at_hash` claim to the ID Token.
> feat(openid): add the openid connect `at_hash` value

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
> Release v1.120.0

- lib/db/mysql/index.js
Whoops, sorry @vbudhram, I accidentally merged https://github.com/mozilla/fxa-oauth-server/pull/612/ before pushing the fix for your capitalization nit; r? for this fixup?
> fix(db): Fix case-consistency of SQL query from #612

- lib/db/mysql/index.js
- npm-shrinkwrap.json
- package.json
> feat(deps): update to bluebird 3

- coverage/blanket.js
- npm-shrinkwrap.json
- package.json
- scripts/test-local.sh
- test/auth_bearer.js
- test/db/mysql.js
Depends on https://github.com/mozilla/fxa-oauth-server/pull/615
> fix(deps): update mocha and other dev deps
